apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-banking-api-deployment
  labels:
    app: go-banking-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-banking-api
  template:
    metadata:
      labels:
        app: go-banking-api
    spec:
      containers:
        - name: go-banking-api
          image: 024848452515.dkr.ecr.eu-central-1.amazonaws.com/go-banking:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http-server
            - containerPort: 9090
              name: grpc-server
          envFrom:
            - secretRef:  
                name: go-banking-secrets