apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-banking-api-ingress-grpc
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
spec:
  ingressClassName: nginx
  rules:
    - host: "gapi.golang-banking.xyz"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: go-banking-api-service
                port:
                  number: 90
  tls:
    - hosts:
        - gapi.golang-banking.xyz
      secretName: golang-banking-gapi-cert
