apiVersion: v1
kind: Service
metadata:
  name: go-banking-api-service
spec:
  selector:
    app: go-banking-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: http-server
      name: http-service
    - protocol: TCP
      port: 9090
      targetPort: grpc-server
      name: grpc-service
  type: ClusterIP
